query GetDecks($authorId: ID) {
  decks(authorId: $authorId) {
    id
    title
    createdAt
    published
    side
    totalRating
    totalRatingCount
    ratings {
      id
      rating
    }
    author {
      id
      username
    }
  }
}
