query GetCards {
  cards {
    id
    type
    cardId
    deploy
    destiny
    forfeit
    gametext
    imageUrl
    lore
    power
    rarity
    set
    side
    subType
    title
    hyperspeed
    defense
    ability
    armor
    landspeed
    maneuver
    gemp_card_id
  }
}
