mutation SetStartingCard($deckId: String!, $deckCardId: ID!, $isStartingCard: Boolean!) {
  setStartingCard(deckId: $deckId, deckCardId: $deckCardId, isStartingCard: $isStartingCard) {
    id
    isStartingCard
  }
}
